version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: cuckoo
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cuckoo

  mysql:
    image: mariadb:10.3
    ports:
      - "33076:3306"
    restart: always
    volumes:
      - type: volume
        target: /var/lib/mysql
      # - ./docker-compose/mysql/init_db.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./dump_prod.sql:/docker-entrypoint-initdb.d/dump.sql
    env_file: .env
    networks:
      - cuckoo

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - cuckoo

networks:
  cuckoo:
    driver: bridge